version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    networks:
      - irmazane_network
    volumes:
      - ./:/app

  redis:
    image: redis:6.2-alpine
    networks:
      - irmazane_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5438:5432
    restart: always
    networks:
      - irmazane_network

networks:
  irmazane_network:
    driver: bridge

volumes:
  postgres_data:
